### ISSUE TITLE
Alert Manager doesnt index alerts when there is a Ä, Ö or Ü in the alert name

### ISSUE THREAD

**Issue by Malic83** [simcen/alert_manager#102]
When there is a ä, ö or ü in the alerts name, Alert Manager doesnt work. The alert doesnt get indexed and therefore doesnt show up in the incident posture.

**Comment by simcen** [comment]
Fixed with 7d7c0814e012274d05680d8a6377a61092914c0f and ed43999c3f124699a4a71792cf7801354b554f99
