### ISSUE TITLE
list of users is not showing up on the incident pop up 

### ISSUE THREAD

**Issue by asimagu** [simcen/alert_manager#113]
the list of users is not showing up on the incident pop up

When I inspect with Firebug , I see that it is returning a 500 Internal Server Error

GET https://<myinstance>:8000/en-US/custom/alert_manager/helpers/get_users?_=1455286083485
	
500 Internal Server Error
		550ms

what am I doing wrong?

Also, would it be possible to retrieve only the users that have certain role assigned??

**Comment by simcen** [comment]
Hi. I just release v2.0.2 with a lot of bugfixes regarding the Users. Can you please update and check if your issue is solved?

About having a certain role: This is a nice idea but currently not supported. Will create an enhancement request separately from this issue.

**Comment by simcen** [comment]
Closing this issue for now as we provided a bugfix. Feel free to reopen if the issue still persists.

Thanks
Simon
