### ISSUE TITLE
alert_manager.py error with urgency field in event

### ISSUE THREAD

**Issue by flle** [simcen/alert_manager#118]
If there is an urgency field in the event (either natively or set via eval) and this field is part of the final result set (with table / fields filtering) passed to alert manager, then the alert_manager.py script exits with error. Log extract from splunkd.log:
`03-22-2016 09:20:19.136 +0100 INFO  sendmodalert - Invoking modular alert action=alert_manager for search="alert_myalert" sid="scheduler__admin_aW5mcmFzdHJ1Y3R1cmVfbW9uaXRvcmluZw__RMD55846704bb6c3ba8d_at_1458634800_53" in app="myapp" owner="admin" type="saved"
03-22-2016 09:20:19.342 +0100 ERROR sendmodalert - action=alert_manager STDERR -  Traceback (most recent call last):
03-22-2016 09:20:19.342 +0100 ERROR sendmodalert - action=alert_manager STDERR -    File "/opt/splunk/etc/apps/alert_manager/bin/alert_manager.py", line 344, in <module>
03-22-2016 09:20:19.342 +0100 ERROR sendmodalert - action=alert_manager STDERR -      metadata.update({ 'urgency': getUrgencyFromResults(results, config['urgency'], incident_id)})
03-22-2016 09:20:19.342 +0100 ERROR sendmodalert - action=alert_manager STDERR -    File "/opt/splunk/etc/apps/alert_manager/bin/alert_manager.py", line 160, in getUrgencyFromResults
03-22-2016 09:20:19.342 +0100 ERROR sendmodalert - action=alert_manager STDERR -      if len(results["fields"]) > 0 and "urgency" in results["fields"][0] and results["fields"][0]["urgency"] in valid_urgencies:
03-22-2016 09:20:19.342 +0100 ERROR sendmodalert - action=alert_manager STDERR -  NameError: global name 'valid_urgencies' is not defined
03-22-2016 09:20:19.356 +0100 INFO  sendmodalert - action=alert_manager - Alert action script completed in duration=218 ms with exit code=1
03-22-2016 09:20:19.356 +0100 WARN  sendmodalert - action=alert_manager - Alert action script returned error code=1
03-22-2016 09:20:19.356 +0100 ERROR sendmodalert - Error in 'sendalert' command: Alert script returned error code 1.
03-22-2016 09:20:19.356 +0100 ERROR SearchScheduler - Error in 'sendalert' command: Alert script returned error code 1., search='sendalert alert_manager results_file="/opt/splunk/var/run/splunk/dispatch/scheduler__admin_aW5mcmFzdHJ1Y3R1cmVfbW9uaXRvcmluZw__RMD55846704bb6c3ba8d_at_1458634800_53/per_result_alert/tmp_0.csv.gz" results_link="https://www....
`

**Comment by IceEyz** [comment]
Just came across this issue as well.

Define
`valid_urgencies = { "low", "medium", "high" }`

or remove from [line 160:](https://github.com/simcen/alert_manager/blob/master/bin/alert_manager.py#L160)
`and results["fields"][0]["urgency"] in valid_urgencies:`

**Comment by simcen** [comment]
Thanks for reporting. Will be fixed with next release
