### ISSUE TITLE
Multivalue Handling Fails in CsvResultParser.py

### ISSUE THREAD

**Issue by johnfromthefuture** [simcen/alert_manager#126]
When a value in a multivalue field is blank, for whatever reason, splunk records '$$' in the results.csv.gz file. This code fails then and throws an unhandled exception:
`matches = re.match(r'\$(.+)\$', val)

values.append(matches.group(1))`

I am planning to test a change in my environment (because this is impacting alert generation for a couple of my alerts) by changing this section to: 
`for val in line[k].split(";"):

    try:

        if val != '$$':

            matches = re.match(r'\$(.+)\$', val)

            values.append(matches.group(1))

    except:

        # Found an issue in the regex match that impacted me and I don't want it to happen again.

        continue`

**Comment by johnfromthefuture** [comment]
Just wanted to add that the fix provided above did correct the issue I was experiencing without impacting operations.

**Comment by simcen** [comment]
Thx for the report, will include this within the next release
