### ISSUE TITLE
SplunkWeb Port and Protocol are hardcoded into Incident Context

### ISSUE THREAD

**Issue by hRun** [simcen/alert_manager#130]
SplunkWeb port "8000" and protocol "http" are hardcoded inside the function setContext() in IncidentContext.py. For support of custom configurations these parameters should be obtained via REST endpoint "/services/server/settings" per instance as done with hostname, version, build, ...

**Comment by simcen** [comment]
Fixed in bba04c80eac59d28db122f9e9c640a8f7d149d5e
