### ISSUE TITLE
ldap right issues

### ISSUE THREAD

**Issue by CLTX** [simcen/alert_manager#132]
Hi guys,

I've installed last version of alert Manager. I have LDAP Login for splunk.
I'm not able to load users:

http://splunk-b2c.falabella.cl/en-GB/custom/alert_manager/helpers/get_users?_=1466536877036 
Failed to load resource: the server responded with a status of 500 (Internal Server Error).

For a while I was able to see all users using splunk internal admin account, but suddenly access got lost.

Thanks,
Carlos.

**Comment by simcen** [comment]
Hi Carlos,
which version are you currently using?
Do you mind sharing web_service.log form $SPLUNK_HOME/var/log/splunkd with us? You can email it to support@alertmanager.info.

Thanks,
Simon

**Comment by simcen** [comment]
Closing this issue for now as there was no feedback. Feel free to reopen.
