### ISSUE TITLE
Issue creating an incident from alerts

### ISSUE THREAD

**Issue by ChrisALadd** [simcen/alert_manager#145]
Posting for a customer:

I am trying to get my triggered alerts to show up as an incident and I am not having any luck.   When I go to the ‘Incident Posture’ dashboard, everything shows up as ‘N/A’
 
In ‘Pivot’, if I add something to ‘Split Rows’ or ‘Split Columns’, I get no rows.

How do I know if I should use ‘Summary indexing’?

The end result I am trying to achieve is to present the events from the alerts to my boss for review and have it tracked that the events were reviewed.  We need to keep history of these events being reviewed for a year for our SOX auditors.

**Comment by simcen** [comment]
I'm closing this now as there is now feedback. Feel free to reopen
