### ISSUE TITLE
Timestamp Issue In modifyincidents.py

### ISSUE THREAD

**Issue by johnfromthefuture** [simcen/alert_manager#147]
I noted that when using `modifyincidents` command, my timestamps were incorrect when the `incident_change` was recorded. This is due to my user context in Splunk GUI being in EDT whereas I run my servers in UTC. For example, submitting a change at 9:20 AM would result in a timestamp: `time=2016-09-22T09:20:00.000000`. The lack of timezone causes splunk to index it as 5:20am instead.

For my environment, I fixed this by changing:
`now = datetime.datetime.now().isoformat()`
to:
`now = datetime.datetime.utcnow().isoformat()`

Maybe something like this would be best:
`now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f%z')`

**Comment by simcen** [comment]
Hey man, thx for the report. Make sense, will fix it in 2.1 branch

**Comment by simcen** [comment]
Note to myself: modifyincidents.py Line 72

**Comment by simcen** [comment]
Unfortunately, datetime.datetime.now() returns a naive timestamp which isn't aware of the timezone. I switched to
now = time.strftime("%Y-%m-%dT%H:%M:%S%z", time.localtime())
which serves now the right timestamp in an ISO format.

**Comment by simcen** [comment]
Fixed in 	eebce51
