### ISSUE TITLE
File alert_handler.py not found

### ISSUE THREAD

**Issue by willianardi** [simcen/alert_manager#149]
Hi,

Downloaded and installed the alert manager app, but file ../../etc/apps/alert_manager/bin/alert_handler.py It is not found.

**Comment by simcen** [comment]
You are most likely referring to an old version of the documentation as alert_handler.py doesn't exist anymore.
Have a look at http://docs.alertmanager.info/Documentation/AlertManager/latest/AlertManager/ConfigureAlerts, which helps you to configure the alerts.

Let me know if this solves your issue.

Thanks
Simon

**Comment by simcen** [comment]
Closing this issue as there was no feedback. Feel free to reopen.
