### ISSUE TITLE
incident changes not applied until splunk restart 

### ISSUE THREAD

**Issue by slacking42** [simcen/alert_manager#153]
i was just making some changes to the display fields and they did not come into effect until after a restart of the splunk services.

I tried using  "https://<yourSplunk>/debug/refresh" but it seems that the app was not refreshed via that route.

Is this expected behavior? If so can I submit a feature request for real time or scheduled update of these fields, or maybe even an app "restart" button similar to the splunk option

Thanks

**Comment by johnfromthefuture** [comment]
To make sure I understand - you changed the display fields for an alert in the Incident Settings page and, when submitted, it didn't change on the Incident Posture page?

In my experience, reloading incident posture page with a simple refresh should handle the display field update. The exception to this is if you also changed the underlying alert and those fields were not available before.

**Comment by slacking42** [comment]
The issue is resolved from tthe last update I believe you can close this out

**Comment by johnfromthefuture** [comment]
Closing per previous comment.
