### ISSUE TITLE
Running Alert Manager in SHC and alert not showing in Incident Posture

### ISSUE THREAD

**Issue by jdeer0618** [simcen/alert_manager#155]
We are running AM in a SHC (didn't see where this was supported, or not) and having issues with alert showing up, particularly after doing bundle deployments after the initial install of AM.

Attached is what the "Incident Posture" table looks like if I move everything in the tstats by clause except `_time` and change the to values that drives the table. Unaltered, the table will only display two alerts. It looks like the alert_handler is struggling. Is it possible that replication happens too fast while the handler is still working?
![screenshot_54](https://cloud.githubusercontent.com/assets/4651176/19569138/4079ba3e-96ba-11e6-8305-ae033aeee4ad.png)

Thanks for taking a look.

**Comment by jdeer0618** [comment]
This is interesting...

It looks like the extractions are not happening which would explain why the results are incomplete. The first attachment here is what I get when I do a `stats count` and a `fillnull`. I hashed the fields so those aren't the actual contents but you get the idea.

The second screenshot is the front end of the raw `alert_metadata` events when I export them to txt. It seems weird that there is so much variability in how the raw alerts are generated.
![screenshot_55](https://cloud.githubusercontent.com/assets/4651176/19578093/c229dbfc-96df-11e6-8a00-41a8d56317f6.png)
![screenshot_56](https://cloud.githubusercontent.com/assets/4651176/19578096/c6be7614-96df-11e6-8b7d-8fae31fc2013.png)

**Comment by jdeer0618** [comment]
Did not mean to close that..

**Comment by johnfromthefuture** [comment]
This looks like the same issue as #173. Closing it out.
