### ISSUE TITLE
Cant see email templates

### ISSUE THREAD

**Issue by Malic83** [simcen/alert_manager#164]
Fresh Splunk 6.5 installation with AM 2.1.3.

Everything seems to work but i cant see any email templates under "Settings" -> "E-Mail Templates".
Just no results found.

I have all the default templates in /default/templates and a few custom ones in /local/templates/
None seem to work and show up.

**Comment by simcen** [comment]
Seems to be a bug, will provide a resolution asap

**Comment by simcen** [comment]
Could you please share alert_manager_migration.log from $SPLUNK_HOME/var/log/splunk? Thanks

**Comment by Malic83** [comment]
There is no alert_manager_migration.log there unfortunately.
There are
alert_manager.log
alert_manager_apimanager.log
alert_manager_controllers.log
alert_manager_eventhandler.log
alert_manager_notifications.log
alert_manager_scheduler.log
alert_manager_suppression_helper.log

**Comment by simcen** [comment]
Ok, that makes sense. Found the issue.

Workaround:
Just add 
`[script://./bin/alert_manager_migrate-v2.0.sh]
disabled = 0

[script://.\bin\alert_manager_migrate-v2.0.path]
disabled = 0`

to $SPLUNK_HOME/etc/apps/alert_manager/local/inputs.conf and restart Splunk. It will create the missing E-mail templates and Notification Scheme.
