### ISSUE TITLE
assign priority based on search result

### ISSUE THREAD

**Issue by slacking42** [simcen/alert_manager#169]
I am looking to assign a priority based on a numeric result from my alert search

I am hoping something like this is feasible?

https://answers.splunk.com/answers/426909/alert-manager-how-to-assign-a-certain-incident-to.html

<$result.field_from_your_search$> being added to the owner field in the alert creation.

**Comment by slacking42** [comment]
never-mind found this 

Default urgency for incidents of this alert.
Note: The urgency can be overriden by a field from search results named 'urgency'. Later, the alert manager calculates a priority based on the impact and urgency. 

as an fyi the link does not go to the documentation for this feature

**Comment by johnfromthefuture** [comment]
Looks like the issue was self-resolved. Closing this to clean out the list of open issues.
