### ISSUE TITLE
Support for Custom Status Definitions

### ISSUE THREAD

**Issue by johnfromthefuture** [simcen/alert_manager#170]
I wanted to expand on my status definitions but they are hardcoded in the incident_posture.js file making it difficult to centrally control. I'm in the process of merging my various changes into the updated development branch code so I can incorporate your fixes and thought I would document this particular change...

I wanted custom status definitions and accomplished it with the modifications below. This does involve changing the alert_status lookup so when Alert Manager is already established in an environment, the KV store should be seeded with the values of that. Also, of note, is that I include a field for "internal only" to mark certain status types as internal. This is done so that status codes used for automation are hidden from the incident update page.

Hope this helps someone.

*File: appserver/static/incident_posture.js*

Around line 432, modified to this:
```    
 var status_url = splunkUtil.make_url('/custom/alert_manager/helpers/get_status_list');
            $.get( status_url,function(data) {
               if (status == "auto_assigned") { status = "assigned"; }
               
               _.each(data, function(val, text) {
                    if (val['status'] == status) {
                        $('#status').append( $('<option></option>').attr("selected", "selected").val(val['status']).html(val['status_description']) )
                    } else {
                        $('#status').append( $('<option></option>').val(val['status']).html(val['status_description']) )
                    }
                    $("#status").prop("disabled", false); 
                });

            }, "json");
```

*File: default/collections.conf*

Added a KV store collection:
```
	[alert_status]
	enforceTypes = true
	field.status = string
	field.status_description = string
	field.internal_only = number
```

*File: default/transforms.conf*

Modified the alert_status lookup. (Note: The intial collection should be seeded with the default status types.)
```
	[alert_status]
	external_type = kvstore
	collection = alert_status
	fields_list = _key, status, status_description, internal_only
```
*File: appserver/controllers/helpers.py*

Added this method definition to the class.

```
    @expose_page(must_login=True, methods=['GET'])
    def get_status_list(self, **kwargs):
        logger.info("Get status list")

        user = cherrypy.session['user']['name']
        sessionKey = cherrypy.session.get('sessionKey')

        uri = '/servicesNS/nobody/alert_manager/storage/collections/data/alert_status?output_mode=json'
        serverResponse, serverContent = rest.simpleRequest(uri, sessionKey=sessionKey)

        logger.info("server_response: %s" % json.dumps(serverResponse))
        entries = json.loads(serverContent)

        status_list = []
        if len(entries) > 0:
            for entry in entries:
                if int(entry['internal_only']) == 0:
                    se = {'status_description': entry['status_description'], 'status': entry['status']}
                    status_list.append(se)

        logger.info("status_list: %s " % json.dumps(status_list))

        return json.dumps(status_list)
```

**Comment by simcen** [comment]
This is great stuff, thanks! 
As discussed at conf - would you like to contribute this directly to the develop branch or would that be too complicated for you as you have a quite different code base?

**Comment by johnfromthefuture** [comment]
At this point, we've come pretty close in our code base. The main
difference I still have left is that I've added a direct integration with
Slack. By putting this functionality direct into Alert Manager, I have
alerts post to Slack only after they are determined to not be suppressed or
duplicate. I'm fairly tapped out on resources now but if you want to add
me, I will contribute as time allows.



John Landers
john@fromthefuture.net

**Comment by johnfromthefuture** [comment]
Added this to the dev branch. Copy/paste from my prod code base. I'm not much of a developer so I'm not sure on etiquette for this kind of stuff - specifically, I'm not sure if I should branch out and merge the branch back in for larger changes like this. Anyway, the code is in place with documentation notes in the checkin info.

I think I mentioned before, this is great because you can have custom status messages without modifying code but any user that upgrades to this will need to seed the KV store with the alert messages.
