### ISSUE TITLE
How to add additional field while setting up an alert action in Alert Manager?

### ISSUE THREAD

**Issue by praveendandu** [simcen/alert_manager#174]
Currently we just have Title, Impact, urgency, owner fields available while setting up alert manager for an alert. I would like to add additional field for ex: message. How can I do that?

**Comment by johnfromthefuture** [comment]
The level of modification depends on the use case. At a minimum, you have to modify the modular alert action. Reference: https://www.splunk.com/blog/2016/08/22/how-to-create-a-modular-alert/

And you'll likely need to modify alert_manager.py to support/process the new option to meet your needs.

**Comment by johnfromthefuture** [comment]
No further action appears to be required here. Closing.
