### ISSUE TITLE
Unable to leave comments

### ISSUE THREAD

**Issue by scottrp21** [simcen/alert_manager#182]
When ever i edit an event and leave a comment i am never able to find that comment. FYI this is amazing.

**Comment by johnfromthefuture** [comment]
Can you run this search and see if your comments are making it into the alerts index? 

`index=alerts sourcetype=incident_change action="comment"`

**Comment by scottrp21** [comment]
ok they do show up there now i should at least be able to track it down as to why its not showing on the Incident Posture dsahboard.

**Comment by AdrianRepublic** [comment]
I am having the exact same issue.

I can see the search is hitting the index but when i add any comment it doesnt show at all

**Comment by my2ndhead** [comment]
Found the issue. The underlying datamodel search does not include action="comment" and it also filters for status=* (which a comment doesn't have...)

To make it work, we have to alter the datamodel. I'll have to check, what we possibly break by doing this.
