### ISSUE TITLE
Incident missing when no owner specified

### ISSUE THREAD

**Issue by cmeerbeek** [simcen/alert_manager#189]
When I open an Incident to change it and I change the status quickly without entering an owner the Incident gets saved without an owner. After this fact I can no longer retrieve the Incident in the reports.
The funny thing is that it is still visible in the big coloured boxes at the top of the Incident Posture dashboard.

Thanks!

<img width="1430" alt="alertmanager-alldata" src="https://user-images.githubusercontent.com/5065560/33082628-89caf5c0-cedd-11e7-9c55-54080e016358.png">
<img width="1423" alt="alertmanager-incposture" src="https://user-images.githubusercontent.com/5065560/33082629-89e3f228-cedd-11e7-8348-9635f053cb70.png">

**Comment by simcen** [comment]
Thanks for your feedback, this has been solved in the current dev tree and will be released along the 2.2 update. 
The solution includes a check so the save button only gets active when both the owner and status dropdown are "ready" as well as a fallback if owner or status are empty to show them anyway in the list of incidents.

**Comment by simcen** [comment]
this is done. release will be published soon
