### ISSUE TITLE
Errors on Active Alerts Dashboard

### ISSUE THREAD

**Issue by hguerrier** [simcen/alert_manager#202]
We're seeing error messages on the Alert Dashboard that should show the count of the alerts. Error is below. This is the most recent version found on Splunkbase.

```
 Dispatch Job: Post-process searches must be transforming searches. The post-process search '| inputlookup alert_manager_priority | join type=outer priority [| `all_alerts` | search status_description=New OR status_description=Assigned* | stats count by priority | fields priority, count] | search priority=informational | fields count | stats count' currently generates events. Update the post-process search so that it transforms the results of the base search '| `all_alerts_single_trend` | timechart count by priority | fillnull value=0 informational, low, medium, high, critical'.
```

**Comment by hguerrier** [comment]
Any word on this?

**Comment by simcen** [comment]
Hi

It looks like this is a custom dashboard built by you.
We do not ship a Dashboard called active_alerts nor we have a lookup called alert_manager_priority. Also the search you posted below is not included anywhere.
Please follow-up with your Splunk Admins.

Thanks
Simon
