### ISSUE TITLE
Incident Posture / Comment emtpy

### ISSUE THREAD

**Issue by benikeller** [simcen/alert_manager#205]
In the incident Posture Dashboard is in the Ticket Drilldown the field comment in the History empty.
Problem is that the comment is written in the action="comment", but the datamodel filters only for action=create OR action=change.

To solve the issue straight forwarder the following changes are requiered to the datamodel:
Add "OR action="comment"" to the constraint of "All Incident Changes"
Add field comment as well to "All Incident Changes"

Afterwards the comment field shows up in the History of every ticket.

See the file attached.
[alert_manager.txt](https://github.com/simcen/alert_manager/files/1785503/alert_manager.txt)

**Comment by my2ndhead** [comment]
Already fixed.
