### ISSUE TITLE
loadincidentresults.py is not getting executed in SHC

### ISSUE THREAD

**Issue by jet1276** [simcen/alert_manager#209]
Hi @simcen,

I just updated my old alert manager in Search Head Cluster environment with Splunk 7.0.0 with new 2.2.0 and i observed that 
`| loadincidentresults $incident_id$` 
is not working in search bar and incident posture page as well. 

Need your help!

**Comment by jet1276** [comment]
Hi @simcen,

I tried in test environment with Single search Head and found that everything is working fine. "loadincidentresults" is not working only in "Search Head Cluster" environment.

**Comment by jet1276** [comment]
Hi Team,

Any development on this?

**Comment by jet1276** [comment]
I think I'll just have to downgrade to older version only. Please let me know whenever in future it's gets addressed.

Thanks.

**Comment by my2ndhead** [comment]
Sorry for the delay....

Can you try to run following search to see if you can see any results?

`| inputlookup incident_results`

**Comment by elf32** [comment]
Changed the Alert Results to use the search provided:
![image](https://user-images.githubusercontent.com/31270076/40807304-762960b6-6513-11e8-873a-a56d39a8d7ce.png)

No results are returned.
![image](https://user-images.githubusercontent.com/31270076/40807244-4b062e82-6513-11e8-94dd-3030fb05157b.png)

**Comment by manderso7** [comment]
using |inputlookup incident_results, I get expected data from the lookup file.

**Comment by jet1276** [comment]
Hi @my2ndhead ,

I am not getting any results in `|inputlookup incident_results` when I run in Search Head Cluster.

But if the same I run in non-cluster environment it is giving the results.

**Comment by my2ndhead** [comment]
@jet1276 Just to be sure, is the "Save incident results to KVStore" checkbox enabled under Settings -> Global Settings ?

**Comment by jet1276** [comment]
Hi @my2ndhead ,

Yes. That was the problem here. checkbox was not enabled. Once I enabled, it started working.

Thanks a lot.
