### ISSUE TITLE
Alert Status Settings are not available in Search Head Cluster

### ISSUE THREAD

**Issue by jet1276** [simcen/alert_manager#210]
Hi @simcen,

Alert Status setting are not visible in Search Head Cluster environment. Its properly visible in Single Search Head Settings, not visible in only in SHC.

Splunk 7.0.0
Search Head Cluster with 3 Members.
Alert Manager 2.2.0
![2018-04-19 18_14_08-alert status _ splunk 7 0 0](https://user-images.githubusercontent.com/13478351/38992170-87b46060-43fd-11e8-9d4d-582c4ec51668.png)

**Comment by my2ndhead** [comment]
Hi @jet1276 

The lookup table should be filled by the bin/alert_manager_migrate-v2.2.sh script run once.

Can you check for any errors in the log files regarding this scripts?
Can you check in local/inputs.conf if the script is already disabled?

Thanks
Mika>

**Comment by jet1276** [comment]
Hi @my2ndhead ,

Yes that was the problem. in local/inputs.conf file the script was already disabled. I enabled it and then pushed the configuration again via deployer. Then I was able to see the Alert Status details.

Though I am getting following errors in Internal logs.


> 2018-04-25 13:37:39,025 WARNING pid="3482" logger="alert_manager_migration" message="KV Store is not yet available, sleeping for 1s." (alert_manager_migrate-v2.0.py:109)


Do I need to explicitly disable `alert_manager_migrate-v2.0.sh` script?
