### ISSUE TITLE
MongoModificationsTracker Warnings

### ISSUE THREAD

**Issue by elf32** [simcen/alert_manager#212]
After upgrading to 2.2.2, the search heads in our cluster began throwing the following warnings every second:
`04-20-2018 17:57:58.431 + 0000 WARN MongoModificationsTracker - Could not load configuration for collection 'drilldown_settings' in application 'alert_manager'. Collection will be ignored.`

The search used to locate these errors was:
`index=_internal sourcetype=splunkd alert_manager`

Any thoughts on a potential cause?

**Comment by my2ndhead** [comment]
This is a leftover from a feature that got dropped...

You can delete the stanza [drilldown_settings] in transforms.conf

https://github.com/simcen/alert_manager/blob/develop/src/default/transforms.conf#L7

**Comment by manderso7** [comment]
Will deleting the drilldown_settings stanza allow us to see the details when we click the drilldown arrow on an incident. Currently, Details is all that shows when we click the drilldown arrow.

**Comment by elf32** [comment]
I was having trouble with the results loading in the dropdown, like you're seeing, and the inline results to display. I had to modify the dashboard to pass the sid and use loadjob instead of loadincidentresults, until I could track down the cause of this.

**Comment by manderso7** [comment]
elf32, could you share your dashboard/incident_posture.js code changes? I'm not sure how to go about changing them as you did. Thank you

**Comment by my2ndhead** [comment]
> Will deleting the drilldown_settings stanza allow us to see the details when we click the drilldown arrow on an incident.

Deleting drilldown_settings has no impact on the details, you can safely remove the stanza

**Comment by manderso7** [comment]
Will it fix the problem of only showing the word Details and not the incident details?

**Comment by my2ndhead** [comment]
Will just fix the MongoModificationsTracker issue.

See: https://github.com/simcen/alert_manager/issues/209 to help debug the incident detail problem.
