### ISSUE TITLE
Free form filter

### ISSUE THREAD

**Issue by osmuse** [simcen/alert_manager#217]
how do you use the free form filter?

**Comment by my2ndhead** [comment]
You can search on following fields:

job_id | incident_id | result_id | _time | alert | title | app | event_search | search | impact | earliest | latest | alert_time | count | category | display_fields | external_reference_id | owner | priority | status | status_description | subcategory | tags | urgency

The filter is in format <field>="<value>". You can also use wildcards or boolean operators to create complexer queries.
