### ISSUE TITLE
Some incidents have no data in "incident results"

### ISSUE THREAD

**Issue by jonwalthour** [simcen/alert_manager#218]
I have an urgent issue that I need your guidance on. We upgraded to alert manager 2.1.4 to 2.2.2. It appears whoever implemented 2.1.4 made configuration changes to the default copies of files because when we upgraded the search head cluster, several settings were back to defaults, including the alerts index being set to main. We got that resolved, but it took some time. In the meantime, we've had many alerts going to the main index. Now, with that straightened out on all three search heads (for a couple of days 1 SH was sending to alerts and the other two to main), I'm still seeing some alerts come in with no "incident results" available. I've tried to make sense of the incident_results lookup to see if I can figure out why some are loading in and others aren't, but I'm stuck. With all the configurations proper and synced on all search heads, why are data missing from the incident_results and how do you think I might fix it?

**Comment by jonwalthour** [comment]
Thank you for all your help, Mika!

**Comment by HoorayJorge** [comment]
What was your solution to this?

**Comment by my2ndhead** [comment]
IIRC under global settings the Save Incidents to KVStore wasn't set.
