### ISSUE TITLE
v2.3.0 Release Date

### ISSUE THREAD

**Issue by jwilczek** [simcen/alert_manager#228]
Version 2.3.0 addresses many feature requests that were preventing us from using this app. We currently have 2.3 installed and are testing. 

Is there a planned release data for 2.3 on splunkbase? Is there an updated TA that accompanies this version? Are there any currently known bugs with this version?

Thank you!

**Comment by my2ndhead** [comment]
Hi

I'm working currently working on a TA release that will pass app certification. The upcoming release should almost be production ready, there are some UI glitches we have to fix before pushing it to Splunkbase. This will take some time...
