### ISSUE TITLE
Will you plan to support Splunk Cloud about Add-on?

### ISSUE THREAD

**Issue by odorusatoshi** [simcen/alert_manager#230]
Hi, I want to use TA ver 2.2.0 into Splunk Cloud environment.
To fix a bug which is related #225 issues I was submitted.
Do you have plan to support for Splunk Cloud?

Thanks,
Satoshi

**Comment by my2ndhead** [comment]
Currently working on a release that can be certified for cloud (limits.conf is preventing this).

Should be ready in the next 1-2 weeks.
