### ISSUE TITLE
App should provide an auto_subsequent_resolve option

### ISSUE THREAD

**Issue by my2ndhead** [simcen/alert_manager#42]
Currently we have an auto_previous_resolve option, that closes existing alerts in state new, when a new alert with the same name is arriving.

This works for use cases, where we don't care about the previous alert, and just want to know which alerts are in an active state.

An alternative use case is, when we want to know how long an alert has persisted. Therefore we need an option to preserve the first incident and close all subsequent alerts.

**Comment by simcen** [comment]
- New incident is getting created and set to status 'auto_subsequent_resolved"
- Event "incident_auto_subsequent_resolved" gets fired (new incident context)
- Pre-existing incident gets history entry mentioning new subsequent resolved incident has been create, including new incident id
- Event "incident_new_subsequent_incident" gets fired (related to pre-existing incident context)
