### ISSUE TITLE
The alert_handler.py script doesn't work with alert mode 'once per result'

### ISSUE THREAD

**Issue by simcen** [simcen/alert_manager#47]
The alert_handler.py script breaks trying to get the job at
`serverResponse, serverContent = rest.simpleRequest(uri, sessionKey=sessionKey, getargs={'output_mode': 'json'})`
(line 115).

**Comment by my2ndhead** [comment]
In my tests, when per result alerting is enabled (with real-time searches) I get different SIDs for each fired alert:
sid=rt_scheduler__admin__search__RMD5bb597fe7dda10157_at_1421496279_8.16
sid=rt_scheduler__admin__search__RMD5bb597fe7dda10157_at_1421496279_8.8
sid=rt_scheduler__admin__search__RMD5bb597fe7dda10157_at_1421496279_8.1

**Comment by my2ndhead** [comment]
Ok. Under each alert there is a per result gz. The parent contains a gz file with all results.

Suggesting fix for extracting the job_id. What is needed is a mechanism, that if the incident is already opened, it should not open another one, but it should still fire a pass-through script as per result.

import re

# Parse arguments
job_path = sys.argv[8]

if os.name == "nt":
    match = re.search(r'dispatch\\([^\\]+)\\', job_path)
     job_id = match.group(1)
else:
     match = re.search(r'dispatch\/([^\/]+)\/', job_path)
     job_id = match.group(1)

#job_id_seg     = len(job_id)-1
#job_id         = job_id[job_id_seg]

**Comment by my2ndhead** [comment]
Please test....

**Comment by my2ndhead** [comment]
Tested on Windows
