### ISSUE TITLE
Incident posture doesn't display incidents when tags are empty

### ISSUE THREAD

**Issue by simcen** [simcen/alert_manager#56]

**Comment by my2ndhead** [comment]
Make sure that inicident settings adds an [untagged] value for tags when saving...

**Comment by simcen** [comment]
tags aren't saved to the incidents collection. They are calculated as a lookup from incident_settings. I just made sure that there won't be an empty value after doing the lookup.

**Comment by my2ndhead** [comment]
Maybe they should also be saved to the incident collection?

**Comment by simcen** [comment]
I don't think so.
The case is to be able to reorganize incidents. When the category, subcategory and tags are saved to each incident, I always have to remember the tag, category or subcategory the incident had in past, when trying to search for them by category, subcategory or tag.
