### ISSUE TITLE
Email does not send when a new owner is assigned

### ISSUE THREAD

**Issue by mkolkebeck** [simcen/alert_manager#61]
Per this Wiki (https://github.com/simcen/alert_manager/wiki/E-Mail-Settings-Guide), "Send an e-mail notification whenever an incident has been created **and assigned** or auto-assigned to a user."

I can receive emails when it is auto-assigned, but not when it is first unassigned and then assigned.  I'm using the latest version (1.1) on a Linux instance.

I don't know if this is a bug or an enhancement request, but I think it's an essential feature of any workflow system.

Thanks!

**Comment by simcen** [comment]
Ok, thanks for reporting this issue. Currently, the whole notification system is in redesign.
But we'll check if we ship a bugfix release.

**Comment by simcen** [comment]
Hi,
I just committed a new implementation to handle notifications, which will support sending emails on manual incident assignment. Basically, you'll be able to define fine-grained notification schemes, at which event a notification should be sent to which recipient.
The change is currently being tested and will be released soon.
Thanks for the patience,
Simon

**Comment by simcen** [comment]
Has been resolved by adding the notification scheme feature with 1de4b6f4aaae3b8223af038b4f336aabd4a4a3be
