### ISSUE TITLE
SMTP authentification doesn't work

### ISSUE THREAD

**Issue by simcen** [simcen/alert_manager#63]
>2015-04-04 20:46:08,747 ERROR Unable to send notification. Continuing without sending notification. >Unexpected Error: Traceback (most recent call last):
>  File "/Volumes/Thunderdisk/Apps/splunk-6.2.1/etc/apps/alert_manager/bin/lib/NotificationHandler.py", >line 272, in send_notification
>    s.login(self.settings["EMAIL_HOST_USER"], self.settings["EMAIL_HOST_PASSWORD"])
>  File "/Volumes/Thunderdisk/Apps/splunk-6.2.1/lib/python2.7/smtplib.py", line 615, in login
>    raise SMTPAuthenticationError(code, resp)
>SMTPAuthenticationError: (535, '5.7.8 Error: authentication failed: authentication failure')

We're using the REST API to get the e-mail server settings configured in Splunk. Unfortunately, Splunk returns the password salted only. Need the clear text password.

**Comment by lkm** [comment]
Should be fixed in #112
