### ISSUE TITLE
Alerts and Emails not sending NOW!!!!

### ISSUE THREAD

**Issue by willcgage** [simcen/alert_manager#70]
After installing Alert Manager, we no longer get email alerts.  We've gone over the installation and configurations, but still not getting anything.

We saved the Alerts in Alert Manager so they would show up, but now we don't see anything.  We are not changing any more as we will lose additional visibility.

Can you think of why this is not working?

Our setup is a search head with two indexers. These indexers are not clustered, but are in two geographical locations.  

![2015-05-07_17-27-21](https://cloud.githubusercontent.com/assets/12308126/7527258/2a2cca56-f4df-11e4-844b-a3d23f74d44a.png)
![2015-05-07_17-30-28](https://cloud.githubusercontent.com/assets/12308126/7527259/2a30ae50-f4df-11e4-817a-e7c85bed18ab.png)

![2015-05-07_17-19-17](https://cloud.githubusercontent.com/assets/12308126/7527115/f69ac496-f4dd-11e4-9454-b6a9542ed215.png)
![2015-05-07_17-20-15](https://cloud.githubusercontent.com/assets/12308126/7527114/f69a4ebc-f4dd-11e4-8f55-68a4834470ef.png)
![2015-05-07_17-20-32](https://cloud.githubusercontent.com/assets/12308126/7527117/f69de46e-f4dd-11e4-8f98-3da41e636060.png)
![2015-05-07_17-21-06](https://cloud.githubusercontent.com/assets/12308126/7527118/f69f52fe-f4dd-11e4-9485-65c5d736b01a.png)
![2015-05-07_17-21-26](https://cloud.githubusercontent.com/assets/12308126/7527116/f69d3654-f4dd-11e4-9e32-2e421d940f39.png)
![2015-05-07_17-23-55](https://cloud.githubusercontent.com/assets/12308126/7527119/f69ffa56-f4dd-11e4-9e6a-9227bac1954d.png)
![2015-05-07_17-18-38](https://cloud.githubusercontent.com/assets/12308126/7527120/f6a47360-f4dd-11e4-9d90-97e7a8507073.png)
![2015-05-07_17-18-49](https://cloud.githubusercontent.com/assets/12308126/7527121/f6a4d38c-f4dd-11e4-9103-beb3d9a66ebb.png)

**Comment by willcgage** [comment]
I can't risk not seeing certain alerts, so for now, we have "uninstalled".

**Comment by willcgage** [comment]
I have log files, but I don't know where to place them.

**Comment by simcen** [comment]
Hi 

Please send the logfiles to simon@balz.me. I'll have a look at them. Please also take notice, that email notifications lack of implementation in version 1.0. The current develop tree in github contains a completely rewritten notification system but needs to be finished first. 

-Simon
