### ISSUE TITLE
User selection drop-downs do not contain/show all users

### ISSUE THREAD

**Issue by flle** [simcen/alert_manager#88]
The user selection drop-down fields to select a user does not show all users. With a large number of (build-in) users, the user list is capped at some number. Affected drop-downs are for example the  incident owner auto-assignment drop-down or the user drop-down in the workflow pop-up window on the incident posture dashboard.
Also, the list does not seem to be ordered strictly alphabetically. A Alert Manager user with the name "alert.group" is at the end of the build-in user list.

Possible solution: especially when users are integrated via AD, build in user lists can get large. So best would probably to populate the list dynamically based on typed user name. Maybe showing Alert Manager users by default.

**Comment by simcen** [comment]
Thanks for the feedback. Since we're migrating to modular alerts in v2.0, we think about a better integration.
